// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPfzz_u5J-ViafVQxBRto55DD-Sq1wLZ8',
    appId: '1:907268974615:web:8133649cfd7ccc8a51d452',
    messagingSenderId: '907268974615',
    projectId: 'ridify-7547d',
    authDomain: 'ridify-7547d.firebaseapp.com',
    storageBucket: 'ridify-7547d.appspot.com',
    measurementId: 'G-XCVGBFGD7W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMeS3BVMdUlGkUA0eOKnyuP_bfE_2z2-A',
    appId: '1:907268974615:android:b798353ae2201bf451d452',
    messagingSenderId: '907268974615',
    projectId: 'ridify-7547d',
    storageBucket: 'ridify-7547d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFbfQvIuUV-zS1NBEV-PU-GNsH4dMDOAw',
    appId: '1:907268974615:ios:a51ba82fd1ea95be51d452',
    messagingSenderId: '907268974615',
    projectId: 'ridify-7547d',
    storageBucket: 'ridify-7547d.appspot.com',
    iosBundleId: 'com.example.ridify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFbfQvIuUV-zS1NBEV-PU-GNsH4dMDOAw',
    appId: '1:907268974615:ios:523e617fd07236b451d452',
    messagingSenderId: '907268974615',
    projectId: 'ridify-7547d',
    storageBucket: 'ridify-7547d.appspot.com',
    iosBundleId: 'com.example.ridify.RunnerTests',
  );
}
